// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebProdavnica2020.Models
{
    [Table("Kategorija")]
    public partial class Kategorija
    {
        public Kategorija()
        {
            Proizvodi = new HashSet<Proizvod>();
        }

        [Key]
        public int KategorijaId { get; set; }
        [Required]
        [StringLength(100)]
        public string Naziv { get; set; }

        [InverseProperty(nameof(Proizvod.Kategorija))]
        public virtual ICollection<Proizvod> Proizvodi { get; set; }
    }
}