// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebProdavnica2020.Models
{
    [Table("Proizvod")]
    public partial class Proizvod
    {
        public Proizvod()
        {
            Stavke = new HashSet<Stavka>();
        }

        [Key]
        public int ProizvodId { get; set; }
        public int? KategorijaId { get; set; }
        [Required]
        [StringLength(100)]
        public string Naziv { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Cena { get; set; }
        [StringLength(100)]
        public string Opis { get; set; }

        [ForeignKey(nameof(KategorijaId))]
        [InverseProperty("Proizvodi")]
        public virtual Kategorija Kategorija { get; set; }
        [InverseProperty(nameof(Stavka.Proizvod))]
        public virtual ICollection<Stavka> Stavke { get; set; }
    }
}