// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebProdavnica2020.Models
{
    [Table("Stavka")]
    public partial class Stavka
    {
        [Key]
        public int StavkaId { get; set; }
        public int PorudzbinaId { get; set; }
        public int ProizvodId { get; set; }
        public int Kolicina { get; set; }

        [ForeignKey(nameof(PorudzbinaId))]
        [InverseProperty("Stavke")]
        public virtual Porudzbina Porudzbina { get; set; }
        [ForeignKey(nameof(ProizvodId))]
        [InverseProperty("Stavke")]
        public virtual Proizvod Proizvod { get; set; }
    }
}